FROM node:latest

# Add a yeoman user because grunt doesn't like being root
RUN adduser --disabled-password --gecos "" yeoman && echo "yeoman ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# set HOME so 'npm install' and 'bower install' don't write to /
ENV HOME /home/yeoman

ENV LANG en_US.UTF-8

RUN mkdir src && chown yeoman:yeoman src && npm i -g yo bower grunt-cli && chown -R yeoman: ~/.npm && chown -R yeoman: /usr/local/lib/node_modules

RUN git config --global url."https://".insteadOf git://

ADD . /home/yeoman/src/generator-appverse-html5

WORKDIR /home/yeoman/src/generator-appverse-html5

RUN npm install && npm link && mkdir /home/yeoman/generated && chmod 777 /home/yeoman/generated && cd /home/yeoman/generated

WORKDIR /home/yeoman/generated

# ENV Variables are not supported on buld and adding the generation on the CMD is too slow... 
RUN yo appverse-html5 --project=/home/yeoman/src/generator-appverse-html5/test/data/appverse-project-rest.json 
RUN yo appverse-html5:app-view view && yo appverse-html5:app-view subview --menu=menu 
RUN yo appverse-html5:rest-entity entity 
RUN yo appverse-html5:rest-entity subentity --menu=menu 
RUN yo appverse-html5:rest-entity subentity --menu=menu --schema=/home/yeoman/src/generator-appverse-html5/test/data/entity-schema.json --rows=100
RUN grunt karma:unit

CMD grunt server